package mas.util;

import jade.util.leap.Serializable;

public class ID implements Serializable{

	private static final long serialVersionUID = 1L;

	//It is recommended to keep each String in ID.java to be kept unique in order to avoid confusion and debugging purpose
	public class MAS {
		public static final String main_container_ipaddress = "127.0.0.1";
	}

	public class Blackboard {
		public static final String Service = "blackboard";
		public static final String LocalName = "blackboard";

		public class BeliefBaseConst{
			public static final String NoOfMachines = "NoOfMachines";
		}

		public class ZoneData {

		}
	}

	public class Customer {
		public static final String Service = "customer";
		public static final String LocalName = "customer";

		public class BeliefBaseConst {
			public static final String JobList = "customerBeliefBase_JobList";
			public static final String JOB_GENERATOR = "customerBeliefBase_JOB-GENERATOR";
			public static final String blackboardAgent = "customerBeliefBase_blackboard-agent";
			public static final String CURRENT_JOB = "customerBeliefBase_Current-job";
		}

		public class ZoneData {

			// contains job generated by customer 
			public static final String newWorkOrderFromCustomer = "customer_newWorkOrderFromCustomer";

			// jobs under negotiation
			public static final String customerJobsUnderNegotiation = "customer_jobsUnderNegotiation";

			// accepted jobs by GSA
			public static final String customerConfirmedJobs = "customer_jobsAccepted";
		}
	}

	public class LocalScheduler {
		public static final String Service = "LSA_machine-simulator-schedule";
		public static final String LocalName = "Local_Scheduling_Agent";

		public class BeliefBaseConst {
			public static final String blackboardAgent = "LSABeliefBase_blackboard-agent";
			public static final String machine = "LSABeliefBase_machine";
			public static final String jobQueue = "LSABeliefBase_job-list";
			public static final String maintAgent = "LSABeliefBase_maintenanceAgent";
			public static final String globalSchAgent = "LSABeliefBase_gsAgent";
			public static final String dataTracker = "LSABeliefBase_data-tracker";
		}

		public class ZoneData {
			// update your waiting time for the job here
			public static final String WaitingTime = "LSA_WaitingTime";

			// update your bid for job here
			public static final String bidForJob = "LSA_BidForJob";

			// update local queue of job of machine
			public static final String machineJobQueue = "LSA_JobQueueForMachine";

			// update the job for machine here
			public static final String jobForMachine = "LSA_jobForMachine";
		}
	}


	public class GlobalScheduler {
		public static final String Service ="global-scheduling-agent";
		public static final String LocalName ="GlobalSchedulingAgent";

		public class ZoneData {
			// final confirmed order coming from customer which has to be accepted
			public static final String GSAConfirmedOrder = "NewJobFromCustomer";

			// jobs under negotiation
			public static final String GSAjobsUnderNegaotiation = "GSA_jobsUnderNegaotiation"; 

			// job which are confirmed after bidding and sent to winner-machine
			public static final String jobForLSA = "GSA_job-for-machine";

			// advertise job for bids from LSA
			public static final String askBidForJobFromLSA = "GSA_ask-for-bid";

			// advertise job for getting waiting time from LSA's
			public static final String GetWaitingTime = "GSA_LocalSchedulingwaiting-time";
		}

		public class BeliefBaseConst {
			public static final String blackboardAgent = "GSA_blackboard-agent";
			public static final String NoOfMachines = "NoOfMachines";
		}
	}

	public class Maintenance {
		public static final String Service="machine-simulator-maint";
		public static final String LocalName ="machine-simulator-maint";

		public class ZoneData {
			// update data for preventive maintenance data for machine
			public static final String prevMaintData = "Maintenance_preventiveMaintenanceData";

			// update data for corrective maintenance data for machine
			public static final String correctiveMaintdata = "Maintenance_correctiveMaintenancedata";

			// update preventive maintenance job for machine here
			public static final String preventiveMaintJob = "Maintenance_preventiveMaintJob";

			// update inspection job data for machine here
			public static final String inspectionJobData = "Maintenance_inspectionData";

			// update inspection job for machine here
			public static final String inspectionJob = "Maintenance_inspectionJob";
		}

		public class BeliefBaseConst {
			public static final String blackboardAgent = "Maintenance_blackboard-agent";
			public static final String machine = "Maintenance_machine";
			public static final String globalSchAgent = "Maintenance_gsAgent";
			public static final String dataTracker = "Maintenance_data-tracker";
			public static final String maintenanceJob = "Maintenance_machine-maintenance-tracker";
		}
	}

	public class Machine{
		public static final String Service="machine_service";
		public static final String LocalName ="machine_simulator";

		public class ZoneData{

			//update new job for the machine
			public static final String askJobFromLSA = "_askJobFromLSA";

			// update machine's health  here
			public static final String myHealth ="machine_health";

			// update the finished job here 
			public static final String finishedJob ="machine_finishedJob";

			// update start of maintenance here
			public static final String maintenanceStart ="machine_maintenanceStart";

			// update start of inspection here
			public static final String inspectionStart ="machine_inspectionStart";

			// update machine's failure here i.e. when machine is failed
			public static final String machineFailures ="machine_machineFailures";
		}
	}
}
